// Generated by CoffeeScript 1.9.0
(function() {
  define(['WebGlConstants'], function(webGlConstants) {
    var canvas, error, gl;
    canvas = document.getElementById(webGlConstants.CANVAS_ID);
    try {
      gl = canvas.getContext(webGlConstants.WEB_GL_CONTEXT_NAME);
      gl = gl != null ? gl : canvas.getContext(webGlConstants.EXPERIMENTAL_WEB_GL_CONTEXT_NAME);
      gl.viewportWidth = canvas.width;
      gl.viewportHeight = canvas.height;
    } catch (_error) {
      error = _error;
      console.log('error initializing webgl');
      console.log(e.message);
    }
    if (!gl) {
      alert('Unable to initialize WebGL. Your browser may not support it.');
      gl = null;
    }
    return {
      getSingleton: function() {
        return gl;
      },
      getCanvas: function() {
        return canvas;
      }
    };
  });

}).call(this);
