// Generated by CoffeeScript 1.9.1
(function() {
  require(['glMatrix-0.9.5.min', 'webgl-utils', 'WebGlConstants', 'shader'], function(glMatrix, webGlUtils, webGlConstants, shader) {
    var config;
    config = {
      vertexShader: shader.vertex,
      fragmentShader: shader.fragment
    };
    return start(config);
  });

}).call(this);
