// Generated by CoffeeScript 1.9.0
(function() {
  require(['glMatrix-0.9.5.min', 'PerspectiveMatrix', 'webgl-utils', 'WebGlConstants', 'GLContext', 'ShapeFactory'], function(glMatrix, pMatrix, webGlUtils, webGlConstants, glContext, ShapeFactory) {
    var animate, cube, currentlyPressedKeys, drawScene, gl, handleKeyDown, handleKeyUp, handleKeys, initBuffers, lastTime, start, tick;
    gl = glContext.getSingleton();
    cube = null;
    initBuffers = function() {
      cube = ShapeFactory.getShape('IlluminatedCube');
      return cube.initBuffers();
    };
    drawScene = function() {
      gl.viewport(0, 0, gl.viewportWidth, gl.viewportHeight);
      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
      mat4.perspective(45, gl.viewportWidth / gl.viewportHeight, 0.1, 100.0, pMatrix);
      return cube.render();
    };
    lastTime = 0;
    animate = function() {
      var elapsed, timeNow;
      timeNow = new Date().getTime();
      if (lastTime !== 0) {
        elapsed = timeNow - lastTime;
        cube.useLighting = document.getElementById('UseLightingCheckbox').checked;
        cube.useBlending = document.getElementById('UseBlendingCheckbox').checked;
        cube.ambientColor[0] = document.getElementById('AmbientColorXInput').value || 0.0;
        cube.ambientColor[1] = document.getElementById('AmbientColorYInput').value || 0.0;
        cube.ambientColor[2] = document.getElementById('AmbientColorZInput').value || 0.0;
        cube.lightDirectionX = document.getElementById('DirectionalLightXInput').value || 0.0;
        cube.lightDirectionY = document.getElementById('DirectionalLightYInput').value || 0.0;
        cube.lightDirectionZ = document.getElementById('DirectionalLightZInput').value || 0.0;
        cube.directionalColor[0] = document.getElementById('DirectionalLightRInput').value || 0.0;
        cube.directionalColor[1] = document.getElementById('DirectionalLightGInput').value || 0.0;
        cube.directionalColor[2] = document.getElementById('DirectionalLightBInput').value || 0.0;
        cube.alpha = document.getElementById('AlphaInput').value || 1.0;
        cube.xRot += (cube.xRotSpeed * elapsed) / 1000.0;
        cube.yRot += (cube.yRotSpeed * elapsed) / 1000.0;
        cube.zRot += (cube.zRotSpeed * elapsed) / 1000.0;
      }
      return lastTime = timeNow;
    };
    tick = function() {
      requestAnimFrame(tick);
      handleKeys();
      drawScene();
      return animate();
    };
    currentlyPressedKeys = {};
    handleKeyDown = function(event) {
      currentlyPressedKeys[event.keyCode] = true;
      if (String.fromCharCode(event.keyCode) === 'F') {
        console.log('F');
        return cube.tickFilter();
      }
    };
    handleKeyUp = function(event) {
      return currentlyPressedKeys[event.keyCode] = false;
    };
    handleKeys = function() {
      if (currentlyPressedKeys[33]) {
        cube.z += 0.5;
      }
      if (currentlyPressedKeys[34]) {
        cube.z -= 0.5;
      }
      if (currentlyPressedKeys[37]) {
        cube.yRotSpeed -= 1;
      }
      if (currentlyPressedKeys[39]) {
        cube.yRotSpeed += 1;
      }
      if (currentlyPressedKeys[38]) {
        cube.xRotSpeed -= 1;
      }
      if (currentlyPressedKeys[40]) {
        return cube.xRotSpeed += 1;
      }
    };
    start = function() {
      initBuffers();
      if (gl) {
        gl.clearColor(0.0, 0.0, 0.0, 1.0);
        gl.enable(gl.DEPTH_TEST);
        gl.depthFunc(gl.LEQUAL);
        gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
      }
      cube.z = -8.0;
      document.onkeydown = handleKeyDown;
      document.onkeyup = handleKeyUp;
      return tick();
    };
    return start();
  });

}).call(this);
