// Generated by CoffeeScript 1.9.0
(function() {
  define(['glMatrix-0.9.5.min'], function(glMatrix) {
    var modelViewMatrix, modelViewMatrixStack, popMatrix, pushMatrix;
    modelViewMatrix = mat4.create();
    modelViewMatrixStack = [];
    pushMatrix = function() {
      var copy;
      copy = mat4.create();
      mat4.set(modelViewMatrix, copy);
      return modelViewMatrixStack.push(copy);
    };
    popMatrix = function() {
      if (modelViewMatrixStack.size === 0) {
        throw "Invalid Pop Matrix";
      }
      return modelViewMatrix = modelViewMatrixStack.pop();
    };
    return modelViewMatrix;
  });

}).call(this);
