// Generated by CoffeeScript 1.9.0
(function() {
  define(['glMatrix-0.9.5.min'], function(glMatrix) {
    var getMatrix, modelViewMatrix, modelViewMatrixStack, popMatrix, pushMatrix;
    modelViewMatrix = mat4.create();
    modelViewMatrixStack = [];
    getMatrix = function() {
      return modelViewMatrix;
    };
    pushMatrix = function() {
      var copy;
      copy = mat4.create();
      mat4.set(modelViewMatrix, copy);
      return modelViewMatrixStack.push(copy);
    };
    popMatrix = function() {
      if (modelViewMatrixStack.size === 0) {
        throw "Invalid Pop Matrix";
      }
      modelViewMatrix = modelViewMatrixStack.pop();
      return modelViewMatrix;
    };
    return {
      getMatrix: function() {
        return getMatrix();
      },
      pushMatrix: function() {
        return pushMatrix();
      },
      popMatrix: function() {
        return popMatrix();
      }
    };
  });

}).call(this);
