// Generated by CoffeeScript 1.9.0
(function() {
  define(['glMatrix-0.9.5.min'], function(glMatrix) {
    var perspectiveMatrix;
    perspectiveMatrix = mat4.create();
    return perspectiveMatrix;
  });

}).call(this);
