// Generated by CoffeeScript 1.9.0
(function() {
  define(['Cube', 'Pyramid'], function(Cube, Pyramid) {
    return {
      getShape: function(type) {
        if (type === 'Cube') {
          return Cube.getInstance();
        } else if (type === 'Pyramid') {
          return Pyramid.getInstance();
        } else {
          return null;
        }
      }
    };
  });

}).call(this);
