// Generated by CoffeeScript 1.9.0
(function() {
  define(['GLContext', 'ModelViewMatrix', 'PerspectiveMatrix', 'glMatrix-0.9.5.min', 'ShaderProgramFactory'], function(glContext, mvMatrix, pMatrix, glMatrix, ShaderProgramFactory) {
    var Star;
    Star = (function() {
      var gl;

      function Star() {}

      gl = glContext.getSingelton();

      return Star;

    })();
    ({
      constructor: function() {
        this.angle = 0;
        this.distance = 0;
        return this.rotationSpeed = 0;
      },
      initBuffers: function() {},
      render: (function(_this) {
        return function() {};
      })(this),
      randomizeColors: function() {
        this.r = Math.random();
        this.g = Math.random();
        return this.b = Math.random();
      }
    });
    return {
      getInstance: function() {
        return new Star();
      }
    };
  });

}).call(this);
