// Generated by CoffeeScript 1.9.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['GLContext', 'ModelViewMatrix', 'PerspectiveMatrix', 'glMatrix-0.9.5.min', 'ShaderProgramFactory'], function(glContext, mvMatrix, pMatrix, glMatrix, ShaderProgramFactory) {
    var TexturedCube;
    TexturedCube = (function() {
      var MAG_FILTERS, MIN_FILTERS, gl;

      gl = glContext.getSingleton();


      /*
      			gl.NEAREST 					# 9728
      			gl.LINEAR 					# 9729
      			gl.NEAREST_MIPMAP_NEAREST 	# 9984
      			gl.LINEAR_MIPMAP_NEAREST 	# 9985
      			gl.NEAREST_MIPMAP_LINEAR 	# 9986
      			gl.LINEAR_MIPMAP_LINEAR 	# 9987
       */

      MIN_FILTERS = [gl.NEAREST, gl.LINEAR, gl.NEAREST_MIPMAP_NEAREST, gl.LINEAR_MIPMAP_NEAREST, gl.NEAREST_MIPMAP_LINEAR, gl.LINEAR_MIPMAP_LINEAR];

      MAG_FILTERS = [gl.NEAREST, gl.LINEAR];

      function TexturedCube() {
        this.animate = __bind(this.animate, this);
        this.render = __bind(this.render, this);
        this.x = this.y = this.z = 0;
        this.xRot = this.yRot = this.zRot = 0;
        this.xRotSpeed = this.yRotSpeed = this.zRotSpeed = 10;
        this.filter = 0;
        this.minFilter = gl.NEAREST;
        this.magFilter = gl.NEAREST;
        this.vertexPositionBuffer = gl.createBuffer();
        this.vertexIndexBuffer = gl.createBuffer();
        this.vertexTextureCoordBuffer = gl.createBuffer();
        this.shaderProgram = ShaderProgramFactory.getInstance('texture.vert', 'texture.frag');
        this.shaderProgram.vertexPositionAttribute = gl.getAttribLocation(this.shaderProgram.program, 'aVertexPosition');
        gl.enableVertexAttribArray(this.shaderProgram.vertexPositionAttribute);
        this.shaderProgram.textureCoordAttribute = gl.getAttribLocation(this.shaderProgram.program, 'aTextureCoord');
        gl.enableVertexAttribArray(this.shaderProgram.textureCoordAttribute);
        this.shaderProgram.pMatrixUniform = gl.getUniformLocation(this.shaderProgram.program, 'uPMatrix');
        this.shaderProgram.mvMatrixUniform = gl.getUniformLocation(this.shaderProgram.program, 'uMVMatrix');
        this.shaderProgram.samplerUniform = gl.getUniformLocation(this.shaderProgram.program, 'uSampler');
        this.crateTextures = {};
        this.initTextures();
      }

      TexturedCube.prototype.initTextures = function() {
        var crateImage, i, j, texture;
        crateImage = new Image();
        i = 0;
        while (i < MAG_FILTERS.length) {
          this.crateTextures[MAG_FILTERS[i]] = {};
          j = 0;
          while (j < MIN_FILTERS.length) {
            texture = gl.createTexture();
            texture.image = crateImage;
            texture.magFilter = MAG_FILTERS[i];
            texture.minFilter = MIN_FILTERS[j];
            this.crateTextures[MAG_FILTERS[i]][MIN_FILTERS[j]] = texture;
            j++;
          }
          i++;
        }
        crateImage.onload = (function(_this) {
          return function() {
            return _this.handleLoadedTextures();
          };
        })(this);
        return crateImage.src = 'images/crate.gif';
      };

      TexturedCube.prototype.handleLoadedTextures = function() {
        var magFilter, minFilter, texture, textureList, _ref, _ref1;
        gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
        _ref = this.crateTextures;
        for (magFilter in _ref) {
          textureList = _ref[magFilter];
          _ref1 = this.crateTextures[magFilter];
          for (minFilter in _ref1) {
            texture = _ref1[minFilter];
            gl.bindTexture(gl.TEXTURE_2D, texture);
            gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.image);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, texture.magFilter);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, texture.minFilter);
            if (texture.minFilter !== gl.NEAREST && texture.minFilter !== gl.LINEAR) {
              gl.generateMipmap(gl.TEXTURE_2D);
            }
          }
        }
        return gl.bindTexture(gl.TEXTURE_2D, null);
      };

      TexturedCube.prototype.initBuffers = function() {
        var elemVertices, textureCoords, vertices;
        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexPositionBuffer);
        vertices = [-1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0];
        gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(vertices), gl.STATIC_DRAW);
        this.vertexPositionBuffer.itemSize = 3;
        this.vertexPositionBuffer.numberOfItems = 24;
        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexTextureCoordBuffer);
        textureCoords = [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0];
        gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(textureCoords), gl.STATIC_DRAW);
        this.vertexTextureCoordBuffer.itemSize = 2;
        this.vertexTextureCoordBuffer.numItems = 24;
        gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this.vertexIndexBuffer);
        elemVertices = [0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7, 8, 9, 10, 8, 10, 11, 12, 13, 14, 12, 14, 15, 16, 17, 18, 16, 18, 19, 20, 21, 22, 20, 22, 23];
        gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, new Uint16Array(elemVertices), gl.STATIC_DRAW);
        this.vertexIndexBuffer.itemSize = 3;
        return this.vertexIndexBuffer.numberOfItems = 36;
      };

      TexturedCube.prototype.render = function() {
        gl.useProgram(this.shaderProgram.program);
        mat4.identity(mvMatrix.getMatrix());
        mat4.translate(mvMatrix.getMatrix(), [this.x, this.y, this.z]);
        mat4.rotate(mvMatrix.getMatrix(), Math.toRadians(this.xRot), [1, 0, 0]);
        mat4.rotate(mvMatrix.getMatrix(), Math.toRadians(this.yRot), [0, 1, 0]);
        mat4.rotate(mvMatrix.getMatrix(), Math.toRadians(this.zRot), [0, 0, 1]);
        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexPositionBuffer);
        gl.vertexAttribPointer(this.shaderProgram.vertexPositionAttribute, this.vertexPositionBuffer.itemSize, gl.FLOAT, false, 0, 0);
        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexTextureCoordBuffer);
        gl.vertexAttribPointer(this.shaderProgram.textureCoordAttribute, this.vertexTextureCoordBuffer.itemSize, gl.FLOAT, false, 0, 0);
        gl.activeTexture(gl.TEXTURE0);
        gl.bindTexture(gl.TEXTURE_2D, this.crateTextures[this.magFilter][this.minFilter]);
        gl.uniform1i(this.shaderProgram.samplerUniform, 0);
        gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this.vertexIndexBuffer);
        gl.uniformMatrix4fv(this.shaderProgram.pMatrixUniform, false, pMatrix);
        gl.uniformMatrix4fv(this.shaderProgram.mvMatrixUniform, false, mvMatrix.getMatrix());
        return gl.drawElements(gl.TRIANGLES, this.vertexIndexBuffer.numberOfItems, gl.UNSIGNED_SHORT, 0);
      };

      TexturedCube.prototype.animate = function() {};

      TexturedCube.prototype.setMinFilter = function(minFilter) {
        return this.minFilter = minFilter;
      };

      TexturedCube.prototype.setMagFilter = function(magFilter) {
        return this.magFilter = magFilter;
      };

      return TexturedCube;

    })();
    return {
      'getInstance': function() {
        return new TexturedCube();
      }
    };
  });

}).call(this);
