// Generated by CoffeeScript 1.9.1
(function() {
  if (window.WebGlConstants == null) {
    window.WebGlConstants = {
      'WEB_GL_CONTEXT_NAME': 'webgl',
      'EXPERIMENTAL_WEB_GL_CONTEXT_NAME': 'experimental-webgl',
      'CANVAS_ID': 'theCanvas',
      'ERROR_MESSAGES': {
        'UNABLE_TO_INITIALIZE_SHADERS': "Could not initialize shaders!"
      }
    };
  }

}).call(this);
